"""Add avatar and phone columns

Revision ID: 92f101ceecfa
Revises: 0006_subscription_entitlements
Create Date: 2026-06-08 10:02:45.452373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92f101ceecfa'
down_revision: Union[str, Sequence[str], None] = '0006_subscription_entitlements'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('analysis_results_session_id_key'), 'analysis_results', type_='unique')
    op.drop_index(op.f('ix_analysis_results_session_id'), table_name='analysis_results')
    op.create_index(op.f('ix_analysis_results_session_id'), 'analysis_results', ['session_id'], unique=True)
    op.add_column('user_profiles', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('avatar_url', sa.Text(), nullable=True))
    op.drop_constraint(op.f('user_profiles_user_id_key'), 'user_profiles', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_profiles_user_id_key'), 'user_profiles', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('user_profiles', 'avatar_url')
    op.drop_column('user_profiles', 'phone')
    op.drop_index(op.f('ix_analysis_results_session_id'), table_name='analysis_results')
    op.create_index(op.f('ix_analysis_results_session_id'), 'analysis_results', ['session_id'], unique=False)
    op.create_unique_constraint(op.f('analysis_results_session_id_key'), 'analysis_results', ['session_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
